name: vhcsite_models
description: Holds the models for VHCSite and VHCSite api
version: 1.0.0
repository: https://github.com/VHCBlade/vhcsite_models

environment:
  sdk: ^3.0.2

dependencies:

  event_db: ^0.1.15

  tuple: ^2.0.0
  
dev_dependencies:
  event_bloc_tester: ^0.1.5
  event_db_tester: ^0.1.0

  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0
